var verse = [
    `For by grace you have been saved through faith; and this is not your own doing, it is the gift of God\n\n<i>EPHESIANS 2:8</i>`,
    `Cast all your anxiety on Him, for He cares about you\n\n<i>1 PETER 5:7</i>`,
    `I believe that I shall see the goodness of the Lord in the land of the living!\n\n<i>PSALM 27:13</i>`,
    `Hitherto you have asked nothing in my name; ask, and you will receive, that your joy may be full\n\n<i>JOHN 16:24</i>`,
    `The least one shall become a clan, and the smallest one a mighty nation; I am the Lord; in its time I will hasten it\n\n<i>ISAIAH 60:22</i>`,
    `And I will make them and the places round about my hill a blessing; and I will send down the showers in their season; they shall be showers of blessing\n\n<i>EZEKIEL 34:26</i>`,
    `Remember not the former things, nor consider the things of old\n\n<i>ISAIAH 43:18</i>`,
    `Let no evil talk come out of your mouths, but only such as is good for edifying, as fits the occasion, that it may impart grace to those who hear\n\n<i>EPHESIANS 4:29</i>`,
    `The way of a fool is right in his own eyes, but a wise man listens to advice\n\n<i>PROVERBS 12:15</i>`,
    `Give to everyone who begs from you; and if anyone takes away your goods, do not ask for them again\n\n<i>LUKE 6:30</i>`,
    `And as you wish that men would do to you, do so to them\n\n<i>LUKE 6:31</i>`,
    `For God has not give us a spirit of timidity but a spirit of power, love, and self-control\n\n<i>2 TIMOTHY 1:7</i>`,
    `God is our refuge and strength, a very present help in trouble\n\n<i>PSALM 46:1</i>`,
    `So Christ, having been offered once to bear the sins of many, will appear a second time, not to deal with sin but to save those who are eagerly waiting for Him\n\n<i>HEBREWS 9:28</i>`,
    `But you, take courage! Do not let your hands be weak, for your work shall be rewarded\n\n<i>2 CHRONICLES 15:7</i>`,
    `For God is not unjust so as to overlook your work and the love which you showed for His sake in serving the saints, as you still do\n\n<i>HEBREWS 6:10</i>`,
    `Come to me, all who labor and are heavy laden, and I will give you rest\n\n<i>MATTHEW 11:28</i>`,
    `Do nothing from selfishness or conceit, but in humility count others better than yourselves\n\n<i>PHILIPPIANS 2:3</i>`,
    `For the word of God is living and active, sharper than any two-edged sword, piercing to the division of soul and spirit, of joints and marrow, and discerning the thoughts and intentions of the heart\n\n<i>HEBREWS 4:12</i>`,
    `He who justifies the wicked and he who condemns the righteous are both alike an abomination to the Lord\n\n<i>PROVERBS 17:15</i>`,
    `Why should a fool have a price in his hand to buy wisdom, when he has no mind?\n\n<i>PROVERBS 17:16</i>`,
    `A friend loves at all times, and a brother is born for adversity\n\n<i>PROVERBS 17:17</i>`,
    `My son, do not forget my teaching, but let your heart keep my commandments; for length of days and years of life and abundant welfare will they give you\n\n<i>PROVERBS 3:1</i>`,
    `Then you will walk on your way securely and your foot will not stumble. If you sit down, you will not be afraid; when you lie down, your sleep will be sweet\n\n<i>PROVERBS 3:23-24</i>`,
    `It is the Lord who goes before you; He will be with you, He will not fail you or forsake you; do not fear or be dismayed\n\n<i>DEUTERONOMY 31:8</i>`,
    `Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort, who comfort us in all our affliction, so that we may be able to comfort with which we ourselves are comforted by God\n\n<i>2 CORINTHIANS 1:3-4</i>`,
    `A man's mind plans his way, but the Lord directs his steps\n\n<i>PROVERBS 16:9</i>`,
    `And the Lord will become King over all the earth; on that day the Lord will be one and His name one\n\n<i>ZECHARIAH 14:9</i>`,
    `But Jesus looked at them and said to them, "With men this is impossible, but with God all things are possible"\n\n<i>MATTHEW 19:26</i>`,
    `Better is a little with the fear of the Lord than great treasure and trouble with it\n\n<i>PROVERBS 15:16</i>`,
    `For thou dost bless the righteous, O Lord; thou dost cover him with favor as with a shield\n\n<i>PSALM 5:12</i>`,
    `Who is wise and understanding among you? By his good life let him show his works in the meekness of wisdom\n\n<i>JAMES 3:13</i>`,
    `But if you have bitter jealousy and selfish ambition in your hearts, do not boast and be false to the truth\n\n<i>JAMES 3:14</i>`,
    `For where jealousy and selfish ambition exist, there will be disorder and every vile practice\n\n<i>JAMES 3:16</i>`,
    `A righteous man who walks in his integrity-blessed are his sons after him!\n\n<i>PROVERBS 20:7</i>`,
    `Love not sleep, lest you come to poverty; open your eyes, and you will have plenty of bread\n\n<i>PROVERBS 20:13</i>`,
    `If the Spirit of Him who raised Jesus from the dead dwells in you, He who raised Christ Jesus from the dead will give life to your mortal bodies also through His Spirit who dwells in you\n\n<i>ROMANS 8:11</i>`,
    `Yet if one suffers as a Christian, let him not be ashamed, but under that name let him glorify God\n\n<i>1 PETER 4:16</i>`,
    `But when you pray, go into your room and shut the door and pray to your Father who is in secret; and your Father who sees in secret will reward you\n\n<i>MATTHEW 6:6</i>`,
    `For  if you forgive men their trespasses, your heavenly Father also will forgive you; but if you do not forgive men their trespasses, neither will your Father forgive your trespasses\n\n<i>MATTHEW 6:14-15</i>`,
    `Keep your heart with all vigilance; for from it flow the springs of life\n\n<i>PROVERBS 4:23</i>`,
    `But the path of the righteous is like the light of dawn, which shines brighter and brighter until full day\n\n<i>PROVERBS 4:18</i>`,
    `So teach us to number our days that we may get a heart of wisdom\n\n<i>PSALM 90:12</i>`,
    `Blessed is the man who trusts in the Lord, whose trust is the Lord\n\n<i>JEREMIAH 17:7</i>`,
    `The heart is deceitful above all things, and desperately corrupt; who can understand it?\n\n<i>JEREMIAH 17:9</i>`,
    `Trust in the Lord forever, for the Lord God is an everlasting rock\n\n<i>ISAIAH 26:4</i>`,
    `Blessed are those whose way is blameless, who walk in the law of the Lord! Blessed are those who keep His testimonies, who seek Him with their whole heart\n\n<i>PSALM 119:1-2</i>`,
    `What you have learned and received and heard and seen in me, do; and the God of peace will be with you\n\n<i>PHILIPPIANS 4:9</i>`,
    `I can do all things in Him who strengthens me\n\n<i>PHILIPPIANS 4:13</i>`,
    `So you, by the help of your God, return, hold fast to love and justice, and wait continually for your God\n\n<i>HOSEA 12:6</i>`,
    `I wait for the Lord, my soul waits, and in His word I hope\n\n<i>PSALM 130:5</i>`,
    `For you were called to freedom, brethren; only do not use your freedom as an opportunity for the flesh, but through love be servants of one another\n\n<i>GALATIANS 5:13</i>`,
    `And every tongue confess that Jesus Christ is Lord, to the glory of God the Father\n\n<i>PHILIPPIANS 2:11</i>`,
    `Set your minds on things that are above, not on things that are on earth\n\n<i>COLOSSIANS 3:2</i>`,
    `For you have died, and your life is hid with Christ in God\n\n<i>COLOSSIANS 3:3</i>`,
    `Blessed is everyone who fears the Lord, who walks in His ways!\n\n<i>PSALM 128:1</i>`,
    `Trust in the Lord with all your heart, and do not rely on your own insight. In all your ways acknowledge Him, and He will make straight your paths\n\n<i>PROVERBS 3:5-6</i>`,
    `And you shall love the Lord your God with all your heart, and with all your soul, and with all your mind, and with all your strength\n\n<i>MARK 12:30</i>`,
    `When the cares of my heart are many, Thy consolations cheer my soul\n\n<i>PSALM 94:19</i>`,
    `But I say to you that hear, Love your enemies, do good to those who hate you, bless those who curse you, pray for those who abuse you\n\n<i>LUKE 6:27-28</i>`,
    `So faith, hope, love, abide these three; but the greatest of these is love\n\n<i>1 CORINTHIANS 13:13</i>`,
    `And though your beginning was small, your latter days will be very great\n\n<i>JOB 8:7</i>`,
    `I know the Lord is always with me\n\n<i>PSALM 16:8</i>`,
    `Finally, brethren, whatever is true, whatever is honorable, whatever is just, whatever is pure, whatever is lovely, whatever is gracious, if there is any excellence, if there is anything worthy of praise, think about these things\n\n<i>PHILIPPIANS 4:8</i>`,
    `Make me to know thy ways, O Lord; teach me thy paths. Lead me in thy truth, and teach me, for thou art the God of my salvation; for thee I wait all the day long\n\n<i>PSALM 25:4-5</i>`,
    `He whose ear heeds wholesome admonition will abide among the wise\n\n<i>PROVERBS 15:31</i>`,
    `Enter His gates with thanksgiving, and His courts with praise! Give thanks to Him, bless His name!\n\n<i>PSALM 100:4</i>`,
    `He is not here; for He has risen, as He said. Come, see the place where He lay\n\n<i>MATTHEW 28:6</i>`,
    `In all your ways acknowledge Him, and He will make straight your paths\n\n<i>PROVERBS 3:6</i>`,
    `Happy is the man who finds wisdom, and the man who gets understanding, for the gain from it is better than gain from silver and its profit better than gold\n\n<i>PROVERBS 3:13-14</i>`,
    `She is more precious than jewels, and nothing you desire can compare with her\n\n<i>PROVERBS 3:15</i>`,
    `One man gives freely, yet grows all the richer; another withholds what he should give, and only suffers want\n\n<i>PROVERBS 11:24</i>`,
    `The Lord lift up His countenance upon you, and give you peace\n\n<i>NUMBERS 6:26</i>`,
    `With all lowliness and meekness, with patience, forbearing one another in love, eager to maintain the unity of the Spirit in the bond of peace\n\n<i>EPHESIANS 4:2-3</i>`,
    `Even a fool who keeps silent is considered wise; when he closes his lips, he is deemed intelligent\n\n<i>PROVERBS 17:28</i>`,
    `O come, let us worship and bow down, let us kneel before the Lord, our Maker!\n\n<i>PSALM 95:6</i>`,
    `But I say, walk by the Spirit, and do not gratify the desires of the flesh\n\n<i>GALATIANS 5:16</i>`,
    `But they who wait for the Lord shall renew their strength, they shall mount up with wings like eagles, they shall run and not be weary, they shall walk and not faint\n\n<i>ISAIAH 40:31</i>`,
    `For where your treasure is, there your heart will also be\n\n<i>MATTHEW 6:21</i>`,
    `Rejoice in your hope, be patient in tribulation, be constant in prayer\n\n<i>ROMANS 12:12</i>`,
    `For the Lord is good; His steadfast love endures forever, and His faithfulness to all generations\n\n<i>PSALM 100:5</i>`,
    `And let the peace of Christ rule in your hearts, to which indeed you were called in the one body\n\n<i>COLOSSIANS 3:15</i>`,
    `And it is my prayer that your love may abound more and more, with knowledge and all discernment\n\n<i>PHILIPPIANS 1:9</i>`,
    `Some boast of chariots, and some of horses; but we boast in the name of the Lord our God\n\n<i>PSALM 20:7</i>`,
    `My flesh and my heart may fail, but God is the strength of my heart and my portion forever\n\n<i>PSALM 73:26</i>`,
    `He who is greatest among you shall be your servant\n\n<i>MATTHEW 23:11</i>`,
    `Thy word is a lamp to my feet and a light to my path\n\n<i>PSALM 119:105</i>`,
    `Thus says the Lord: "Keep your voice from weeping, and your eyes from tears; for your work shall be rewarded", says the Lord and they shall come back from the land of the enemy\n\n<i>JEREMIAH 31:16</i>`,
    `"There is hope for your future", says the Lord, and your children shall come back to their own country\n\n<i>JEREMIAH 31:17</i>`,
    `The true light that enlightens every man was coming into the world\n\n<i>JOHN 1:9</i>`,
    `We know that in everything God works for good with those who love Him, who are called according to His purpose\n\n<i>ROMANS 8:28</i>`,
    `But seek first His kingdom and His righteousness, and all these things shall be yours as well\n\n<i>MATTHEW 6:33</i>`,
    `The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?\n\n<i>PSALM 27:1</i>`,
    `O give thanks to the Lord, for He is good; His steadfast love endures forever!\n\n<i>PSALM 118:1</i>`,
    `In God I trust without a fear. What can man do to me?\n\n<i>PSALM 56:11</i>`,
    `Looking to Jesus the pioneer and perfecter of our faith, who for the joy that was set before Him endured the cross, despising the shame, and is seated at the right hand of the throne of God\n\n<i>HEBREW 12:2</i>`,
    `There is one whose rash words are like sword thrusts, but the tongue of the wise brings healing\n\n<i>PROVERBS 12:18</i>`,
    `And God is able to provide you with every blessing in abundance, so that you may always have enough of everything and may provide in abundance for every good work\n\n<i>2 CORINTHIANS 9:8</i>`,
    `I thank my God in all my remembrance of you\n\n<i>PHILIPPIANS 1:3</i>`,
    `No, in all these things we are more than conquerors through Him who loved us\n\n<i>ROMANS 8:37</i>`,
    `And when he said this, he breathed on them, and said to them, "Receive the Holy Spirit"\n\n<i>JOHN 20:22</i>`,
    `For still the vision awaits its time; it hastens to the end-it will not lie. If it seem slow, wait for it; it will surely come, it will not delay\n\n<i>HABAKKUK 2:3</i>`,
    `For I, the Lord your God, hold your right hand; it is I who say to you, "Fear not, I will help you"\n\n<i>ISAIAH 41:13</i>`,
    `But I will sing of thy might; I will sing aloud of thy steadfast love in the morning. For thou hast been to me a fortress and a refuge in the day of my distress\n\n<i>PSALM 59:16</i>`,
    `Therefore if anyone is in Christ, he is a new creation; the old has passed away, behold, the new has come\n\n<i>2 CORINTHIANS 5:17</i>`,
    `Instead of your shame you shall have a double portion, instead of dishonor you shall rejoice in your lot; therefore in your land you shall possess a double portion;\n\n<i>ISAIAH 61:7</i>`,
    `For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord\n\n<i>ROMANS 6:23</i>`,
    `You are the light of the world. A city set on a hill cannot be hid\n\n<i>MATTHEW 5:14</i>`,
    `Then Haggai, the messenger of the Lord, spoke to the people with the Lord's message, "I am with you, says the Lord"\n\n<i>HAGGAI 1:13</i>`,
    `Blessed be the God and Father of our Lord Jesus Christ! By His great mercy we have been born anew to a living hope through the resurrection of Jesus Christ from the dead\n\n<i>1 PETER 1:3</i>`,
    `Again Jesus spoke to them, saying, "I am the light of the world; he who follows me will not walk in darkness, but will have the light of life"\n\n<i>JOHN 8:12</i>`,
    `Do not be conformed to this world but be transformed by the renewal of your mind, that you may prove what is the will of God, what is good and acceptable and perfect\n\n<i>ROMANS 12:2</i>`,
    `Know this, my beloved brethren. Let every man be quick to hear, slow to speak, slow to anger\n\n<i>JAMES 1:19</i>`,
    `By this we know love, that He laid down His life for us; and we ought to lay down our lives for the brethren\n\n<i>1 JOHN 3:16</i>`,
    `And we have seen and testify that the Father has sent His son as the Savior of the World\n\n<i>1 JOHN 4:14</i>`,
    `Whoever confesses that Jesus is the Son of God, God abides in him, and he in God\n\n<i>1 JOHN 4:15</i>`,
    `There thou art great, O Lord God; for there is none like thee, and there is no God besides thee, according to all that we have heard with our ears\n\n<i>2 SAMUEL 7:22</i>`,
    `And whatever you do, in word or deed, do everything in the name of the Lord Jesus, giving thanks to God the Father through Him\n\n<i>COLOSSIANS 3:17</i>`,
    `Wives, be subject to your husbands, as is fitting in the Lord. Husbands, love your wives, and do not be harsh with them\n\n<i>COLOSSIANS 3:18-19</i>`,
    `Children, obey your parents in everything, for this pleases the Lord\n\n<i>COLOSSIANS 3:20</i>`,
    `Fathers, do not provoke your children, lest they become discouraged\n\n<i>COLOSSIANS 3:21</i>`,
    `Slaves, obey in everything those who are your earthly masters, not with eyeservice, as men-pleasers, but in singleness of heart, fearing the Lord\n\n<i>COLOSSIANS 3:22</i>`,
    `Whatever your task, work heartily, as serving the Lord and not men\n\n<i>COLOSSIANS 3:23</i>`,
    `Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom\n\n<i>2 CORINTHIANS 3:17</i>`,
    `Have I not commanded you? Be strong and of good courage; be not frightened, neither be dismayed; for the Lord your God is with you wherever you go\n\n<i>JOSHUA 1:9</i>`,
    `Search me, O God, and know my heart! Try me and know my thoughts!\n\n<i>PSALM 139:23</i>`,
    `The true light that enlightens every man was coming into the world\n\n<i>JOHN 1:9</i>`,
    `Forbearing one another and, if one has a complaint against another, forgiving each other; as the Lord has forgiven you, so you also must forgive\n\n<i>COLOSSIANS 3:13</i>`,
    `Because, if you confess with your lips that Jesus is Lord and believe in your heart that God raised Him from the dead, you will be saved\n\n<i>ROMANS 10:9</i>`,
    `For man believes with his heart and so is justified, and he confesses with his lips and so is saved\n\n<i>ROMANS 10:10</i>`,
    `The scripture says, "No one who believes in Him will be put to shame"\n\n<i>ROMANS 10:11</i>`,
    `In all things I have shown you that by so toiling one must help the weak, remembering the words of the Lord Jesus, how He said, "It is more blessed to give than to receive"\n\n<i>ACTS 20:35</i>`,
    `By faith we understand that the world was created by the word of God, so that what is seen was made out of things which do not appear\n\n<i>HEBREWS 11:3</i>`,
    `And without faith it is impossible to please God. For whoever would draw near to God must believe that He exists and He rewards those who seek Him\n\n<i>HEBREWS 11:6</i>`,
    `The Lord is my strength and my song, and He has become my salvation; this is my God, and I will praise Him, my father's God, and I will exalt Him\n\n<i>EXODUS 15:2</i>`,
    `But thou, O Lord, art a shield about me, my glory, and the lifter of my head\n\n<i>PSALM 3:3</i>`,
    `I lie down and sleep; I wake again, for the Lord sustains me\n\n<i>PSALM 3:5</i>`,
    `Every way of a man is right in his own eyes, but the Lord weighs the heart\n\n<i>PROVERBS 21:2</i>`,
    `To do righteousness and justice is more acceptable to the Lord than sacrifice\n\n<i>PROVERBS 21:3</i>`,
    `I write this to you who believe in the name of the Son of God, that you may know that you have eternal life\n\n<i>1 JOHN 5:13</i>`,
    `And this is the confidence which we have in Him, that if we ask anything according to His will He hears us\n\n<i>1 JOHN 5:14</i>`,
    `And if we know that He hears us in whatever we ask, we know that we have obtained the requests made made of Him\n\n<i>1 JOHN 5:15</i>`,
    `All wrongdoing is sin, but there is sin which is not mortal\n\n<i>1 JOHN 5:17</i>`,
    `But thanks be to God, who gives us the victory through our Lord Jesus Christ\n\n<i>1 CORINTHIANS 15:57</i>`,
    `Therefore, my beloved brethren, be steadfast, immovable, always abounding in the work of the Lord, knowing that in the Lord, your labor is not in vain\n\n<i>1 CORINTHIANS 15:58</i>`,
    `For He has made known to us in all wisdom and insight the mystery of His will, according to His purpose which He set forth in Christ as a plan for the fulness of time, to unite all things in Him, things in heaven and things on earth\n\n<i>EPHESIANS 1:9-10</i>`,
    `But when you give alms, do not let your left hand know what your right hand is doing, so that your alms may be in secret; and your Father who sees in secret will reward you\n\n<i>MATTHEW 6:3-4</i>`,
    `Then He touched their eyes, saying, "According to your faith be it done to you"\n\n<i>MATTHEW 9:29</i>`,
    `For we walk by faith, not by sight\n\n<i>2 CORINTHIANS 5:7</i>`,
    `For I am sure that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers, nor height, nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord\n\n<i>ROMANS 8:38-39</i>`,
    `And if I have prophetic powers, and understand all mysteries and all knowledge, and if I have all faith, so as to move mountains, but have not love, I am nothing\n\n<i>1 CORINTHIANS 13:2</i>`,
    `Love is patient and kind; love is not jealous or boastful; it is not arrogant or rude. Love does not insist on its own way; it is not irritable or resentful;\n\n<i>1 CORINTHIANS 13:4-5</i>`,
    `Love bears all things, believes all things, hopes all things, endures all things\n\n<i>1 CORINTHIANS 13:7</i>`,
    `Rejoice in the Lord always; again I will say, Rejoice. Let all men know your forbearance. The Lord is at hand\n\n<i>PHILIPPIANS 4:4-5</i>`,
    `Let love be genuine; hate what is evil, hold fast to what is good; love one another with brotherly affection; outdo one another in showing honor\n\n<i>ROMANS 12:9-10</i>`,
    `May the Lord give strength to His people! May the Lord bless His people with peace!\n\n<i>PSALM 29:11</i>`,
    `Fear not, for I am with you, be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my victorious right hand\n\n<i>ISAIAH 41:10</i>`,
    `Then my enemies will be turned back in the day when I call. This I know, that God is for me\n\n<i>PSALM 56:9</i>`,
    `And walk in love, as Christ loved us and gave Himself up for us, a fragrant offering and sacrifice to God\n\n<i>EPHESIANS 5:2</i>`,
    `I have said this to you, that in Me you may have peace. In the world you have tribulation; but be of good cheer, I have overcome the world\n\n<i>JOHN 16:33</i>`,
    `From the rising of the sun to its setting the name of the Lord is to be praised!\n\n<i>PSALM 113:3</i>`,
    `The Lord is high above all nations, and His glory above the heavens!\n\n<i>PSALM 113:4</i>`,
    `Count it all joy, my brethren, when you meet various trials, for you know that the testing of your faith produces steadfastness\n\n<i>JAMES 1:2-3</i>`,
    `If any of you lacks wisdom, let him ask God, who gives to all men generously and without reproaching, and it will be given him\n\n<i>JAMES 1:5</i>`,
    `For the mountains may depart and the hills be removed, but my steadfast love shall not depart from you, and my covenant of peace shall not be removed, says the Lord, who has compassion on you\n\n<i>ISAIAH 54:10</i>`,
    `I know that thou canst do all things, and that no purpose of thine can be thwarted\n\n<i>JOB 42:2</i>`,
    `When you vow a vow to God, do not delay paying it; for He has no pleasure in fools. Pay what you vow. It is better that you should not vow than that you should vow and not pay\n\n<i>ECCLESIASTES 5:4-5</i>`,
    `But He was wounded for our transgressions, He was bruised for our iniquities; upon Him was the chastisement that made us whole, and with His stripes we are healed\n\n<i>ISAIAH 53:5</i>`,
    `But let him ask in faith, with no doubting, for he who doubts is like a wave of the sea that is driven and tossed by the wind\n\n<i>JAMES 1:6</i>`,
    `Hear this, O Job; stop and consider the wondrous works of God\n\n<i>JOB 37:14</i>`,
    `So we fasted and besought our God for this, and He listened to our entreaty\n\n<i>EZRA 8:23</i>`,
    `Even though I walk through the valley of the shadow of death, I fear no evil; for thou art with me; thy rod and thy staff, they comfort me\n\n<i>PSALM 23:4</i>`,
    `He shall build a house for me, and I will establish His throne forever\n\n<i>1 CHRONICLES 17:12</i>`,
    `For a day in thy courts is better than a thousand elsewhere. I would rather be a doorkeeper in the  house of my God than dwell in the tents of wickedness\n\n<i>PSALM 84:10</i>`,
    `For the Lord God is a sun and shield; he bestows favor and honor. No good thing does the Lord withhold from those who walk uprightly\n\n<i>PSALM 84:11</i>`,
    `Behold, God is my salvation; I will trust, and will not be afraid; for the Lord God is my strength and my song, and He has become my salvation\n\n<i>ISAIAH 12:2</i>`,
    `Then He said to me, "Fear not, Daniel, for from the first day that you set your mind to understand and humbled yourself before your God, your words have been heard, and I have come because of your words"\n\n<i>DANIEL 10:12</i>`,
    `If my people who are called by my name humble themselves, and pray and seek my face and turn from their wicked ways, then I will hear from heaven, and will forgive their sin and heal their land\n\n<i>2 CHRONICLES 7:14</i>`,
    `He will swallow up death forever, and the Lord God will wipe away tears from all faces, and the reproach of His people He will take away from all the earth; for the Lord has spoken\n\n<i>ISAIAH 25:8</i>`,
    `Peace I leave with you; my peace I give to you; not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid\n\n<i>JOHN 14:27</i>`,
    `Then you shall call, and the Lord will answer; you shall cry, and He will say, Here I am.\n\n<i>ISAIAH 58:9</i>`,
    `To set the mind on the flesh is death, but to set the mind on the Spirit is life and peace\n\n<i>ROMANS 8:6</i>`,
    `The end of the matter; all has been heard. Fear God, and keep His commandments; for this is the whole duty of man\n\n<i>ECCLESIASTES 12:13</i>`,
    `For the eyes of the Lord are upon the righteous, and His ears are open to their prayer. But the face of the Lord is against those that do evil\n\n<i>1 PETER 3:12`,
    `No greater joy can I have than this, to hear that my children follow the truth\n\n<i>3 JOHN 1:4</i>`,
    `Be strong and of good courage, do not fear or be in dread of them: for it is the Lord your God who goes with you; He will not fail you or forsake you\n\n<i>DEUTORONOMY 31:6</i>`,
    `For everyone who asks receives, and he who seeks finds, and to him who knocks it will be opened\n\n<i>MATTHEW 7:8</i>`,
    `Jesus said to him, "I am the way, and the truth, and the life; no one comes to the Father, but by me"\n\n<i>JOHN 14:6</i>`,
    `And he said to him, "You shall love the Lord your God with all your heart, and with all your soul, and with all your mind"\n\n<i>MATTHEW 22:37</i>`,
    `I consider that the sufferings of this present time are not worth comparing with the glory that is to be revealed to us\n\n<i>ROMANS 8:18</i>`,
    `But I say to you that hear, Love your enemies, do good to those who hate you, bless those who curse you, pray for those who abuse you\n\n<i>LUKE 6:27-28</i>`,
    `O give thanks to the Lord, for He is good; for His steadfast love endures forever!\n\n<i>1 CHRONICLES 16:34</i>`,
    `Grace to you and peace from God our Father and the Lord Jesus Christ\n\n<i>2 CORINTHIANS 1:2`,
    `Keep your life free from love of money, and be content with what you have; for He has said, "I will never fail you nor forsake you"\n\n<i>HEBREWS 13:5</i>`,
    `But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness and self-control; against such there is no law\n\n<i>GALATIANS 5:22-23</i>`,
    `Turn back, and say to Hezeki'ah the prince of my people, Thus says the Lord, the God of David your father: I have heard your prayer, I have seen your tears; behold, I will heal you; on the third day you shall go up to the house of the Lord\n\n<i>2 KINGS 20:5</i>`,
    `Pray constantly\n\n<i>1 THESSALONIANS 5:17</i>`,
    `Many are the plans in the mind of a man, but it is the purpose of the Lord that will be established\n\n<i>PROVERBS 19:21</i>`,
    `Take delight in the Lord, and He will give you the desires of your heart\n\n<i>PSALM 37:4`,
    `The Lord your God who goes before you will Himself fight for you, just as He did for you in Egypt before your eyes\n\n<i>DEUTERONOMY 1:30</i>`,
    `Yes, the Lord will give what is good, and our land will yield its increase\n\n<i>PSALM 85:12</i>`,
    `Righteousness will go before him, and make his footsteps a way\n\n<i>PSALM 85:13</i>`,
    `There is none holy like the Lord, there is none besides thee; there is no rock like our God\n\n<i>1 SAMUEL 2:2</i>`,
    `Have no anxiety about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God\n\n<i>PHILIPPIANS 4:6`,
    `Better is a dinner of herbs where love is than a fatted ox and hatred with it\n\n<i>PROVERBS 15:17</i>`,
    `Let not your hearts be troubled; believe in God, believe also in Me\n\n<i>JOHN 14:1</i>`,
    `A gentle tongue is a tree of life, but perverseness in it breaks the spirit\n\n<i>PROVERBS 15:4</i>`,
    `When you pass through the waters I will be with you; and through the rivers, they shall not overwhelm you; when you walk through fire you shall not be burned, and the flame shall not consume you\n\n<i>ISAIAH 43:2</i>`,
    `Now faith is the assurance of things hoped for, the conviction of things not seen\n\n<i>HEBREWS 11:1</i>`,
    `But God shows His love for us in that while we were yet sinners Christ died for us\n\n<i>ROMANS 5:8</i>`,
    `And be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you\n\n<i>EPHESIANS 4:32</i>`,
    `There is no fear in love, but perfect love casts out fear. For fear has to do with punishment, and he who fears is not perfected in love\n\n<i>1 JOHN 4:18</i>`,
    `We love, because He first loved us\n\n<i>1 JOHN 4:19</i>`,
    `If anyone says, "I love God," and hates his brother, he is a liar; for he who does not love his brother whom he has seen, cannot love God whom he has not seen\n\n<i>1 JOHN 4:20</i>`,
    `Beloved, I pray that all may go well with you and that you may be in health; I know that it is well with your soul\n\n<i>3 JOHN 1:2</i>`,
    `Oil and perfume make the heart glad, but the soul is torn by trouble\n\n<i>PROVERBS 27:9</i>`,
    `He who blesses his neighbor with a loud voice, rising early in the morning, will be counted as cursing\n\n<i>PROVERBS 27:14</i>`,
    `There are friends who pretend to be friends, but there is a friend who sticks closer than a brother\n\n<i>PROVERBS 18:24</i>`,
    `And after you have suffered a little while, the God of all grace, who has called you to His eternal glory in Christ, will Himself restore, establish, and strengthen you\n\n<i>1 PETER 5:10</i>`,
    `The Lord is a stronghold to him whose way is upright, but destruction to evildoers\n\n<i>PROVERBS 10:29</i>`,
    `So then, as we have opportunity, let us do good to all men, and especially to those who are of the household of faith\n\n<i>GALATIANS 6:10</i>`,
    `The grace of the Lord Jesus Christ be with your spirit, brethren. Amen\n\n<i>GALATIANS 6:18</i>`,
    `The Lord is not slow about His promise as some count slowness, but is forbearing toward you, not wishing that any should perish, but that all should reach repentance\n\n<i>2 PETER 3:9</i>`,
    `Commit your way to the Lord; trust in Him, and He will act\n\n<i>PSALM 37:5</i>`,
    `Above all hold unfailing your love for one another, since love covers a multitude of sins\n\n<i>1 PETER 4:8</i>`,
    `I will sprinkle clean water upon you, and you shall be clean from all your uncleannesses, and from all your idols I will cleanse you\n\n<i>EZEKIEL 36:25</i>`,
    `Many are the afflictions of the righteous; but the Lord delivers him out of them all\n\n<i>PSALM 34:19</i>`,
    `You shall serve the Lord your God, and I will bless your bread and your water; and I will take sickness away from the midst of you\n\n<i>EXODUS 23:25</i>`,
    `But, as it is written, "What no eye has seen, nor ear heard, nor the heart of man conceived, what God has prepared for those who love Him,"\n\n<i>1 CORINTHIANS 2:9</i>`,
    `For in it the righteousness of God is revealed through faith for faith; as it is written, "He who through faith is righteous shall live."\n\n<i>ROMANS 1:17</i>`,
    `For I know the plans I have for you, says the Lord, plans for welfare and not for evil, to give you a future and a hope\n\n<i>JEREMIAH 29:11</i>`,
    `Then you will call upon me and come and pray to me, and I will hear you\n\n<i>JEREMIAH 29:12</i>`,
    `Jesus said to her, "I am the resurrection and the life; he who believes in Me, though he die, yet shall he live, and whoever lives and believes in Me shall never die. Do you believe this?"\n\n<i>JOHN 11:25-26</i>`,
    `Rejoice always, pray constantly, give thanks in all circumstances; for this is the will of God in Christ Jesus for you\n\n<i>1 THESSALONIANS 5:16-18</i>`,
    `The Lord is good, a stronghold in the day of trouble; He knows those who take refuge in Him\n\n<i>NAHUM 1:7</i>`,
    `No evil shall befall you, no scourge come near your tent. For He will give His angels charge of you to guard you in all your ways\n\n<i>PSALMS 91:10-11</i>`,
    `"Yet even now," says the Lord, "return to me with all your heart, with fasting, with weeping, and with mourning;"\n\n<i>JOEL 2:12</i>`,
    `After these things the word of the Lord came to Abram in a vision, "Fear not, Abram, I am your shield; your reward shall be very great"\n\n<i>GENESIS 15:1</i>`,
    `Awaiting our blessed hope, the appearing of the glory of our great God and Savior Jesus Christ\n\n<i>TITUS 2:13</i>`,
    `The righteous will never be removed, but the wicked will not dwell in the land\n\n<i>PROVERBS 10:30</i>`,
    `Behold, I am with you and will keep you wherever you go, and will bring you back to this land; for I will not leave you until I have done that of which I have spoken to you\n\n<i>GENESIS 28:15</i>`,
    `But He said to me, "My grace is sufficient for you, for my power is made perfect in weakness." I will all the more gladly boast of my weaknesses, that the power of Christ may rest upon me\n\n<i>2 CORINTHIANS 12:9</i>`,
    `And He said to them, "Take heed, and beware of all covetousness; for a man's life does not consist in abundance of his possessions"\n\n<i>LUKE 12:15</i>`,
    `Thou art my hiding place and my shield; I hope in thy word\n\n<i>PSALM 119:114</i>`,
    `Can a woman forget her sucking child, that she should have no compassion on the son of her womb? Even these may forget, yet I will not forget you\n\n<i>ISAIAH 49:15</i>`,
    `Be not afraid of them, for I am with you to deliver you, says the Lord\n\n<i>JEREMIAH 1:8</i>`,
    `Commit your work to the Lord, and your plans will be established\n\n<i>PROVERBS 16:3</i>`,
    `When a man's ways please the Lord, He makes even his enemies to be at peace with him\n\n<i>PROVERBS 16:7</i>`,
    `Better is a little with righteousness than great revenues with injustice\n\n<i>PROVERBS 16:8</i>`,
    `Hence I remind you to rekindle the Gift of God that is within you through the laying on of my hands\n\n<i>2 TIMOTHY 1:6</i>`,
    `O come, let us sing to the Lord; let us make a joyful noise to the rock of our salvation!\n\n<i>PSALM 95:1</i>`,
    `Let brotherly love continue\n\n<i>HEBREWS 13:1</i>`,
    `Do not neglect to show hospitality to strangers, for thereby some have entertained angels unawares\n\n<i>HEBREWS 13:2</i>`,
    `Hence we can confidently say, "The Lord is my helper, I will not be afraid; what can man do to me?"\n\n<i>HEBREWS 13:6</i>`,
    `Judge not, and you will not be judged; condemn not, and you will not be condemned; forgive, and you will be forgiven;\n\n<i>LUKE 6:37</i>`,
    `Do not be deceived; God is not mocked, for whatever a man sows, that he will also reap\n\n<i>GALATIANS 6:7</i>`,
    `And let us not grow weary in well-doing, for in due season we shall reap, if we do not lose heart\n\n<i>GALATIANS 6:9</i>`,
    `Wait for the Lord; be strong, and let your heart take courage; yes, wait for the Lord!\n\n<i>PSALM 27:14</i>`,
    `The Lord is just in all His ways, and kind in all His doings\n\n<i>PSALM 145:17</i>`,
    `The Lord is near to all who call upon Him, to all who call upon Him in truth\n\n<i>PSALM 145:18</i>`,
    `On the glorious splendor of thy majesty, and on thy wondrous works, I will meditate\n\n<i>PSALM 145:5</i>`,
    `Remember the wonderful works that He has done, His miracles, and the judgments He uttered\n\n<i>PSALM 105:5</i>`,
    `And the peace of God, which passes all understanding, will keep your hearts and your minds in Christ Jesus\n\n<i>PHILIPPIANS 4:7</i>`,
    `Two are better than one, because they have a good reward for their toil\n\n<i>ECCLESIASTES 4:9</i>`,
    `Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you\n\n<i>MATTHEW 7:7</i>`,
    `Wisdom builds her house, but folly with her own hands tears it down\n\n<i>PROVERBS 14:1</i>`,
    `Leave the presence of a fool, for there you do not meet words of knowledge\n\n<i>PROVERBS 14:7</i>`,
    `He has made everything beautiful in its time; also He has put eternity into man's mind, yet so that he cannot find out what God has done from the beginning to the end\n\n<i>ECCLESIASTES 3:11</i>`,
    `He who forgives an offense seeks love, but he who repeats a matter alienates a friend\n\n<i>PROVERBS 17:9</i>`,
    `O give thanks to the Lord, for He is good; for His steadfast love endures forever!\n\n<i>PSALM 107:1</i>`,
    `But to all who received Him, who believed in His name, He gave power to become children of God;\n\n<i>JOHN 1:12</i>`,
    `And the Word became flesh and dwelt among us, full of grace and truth; we have beheld His glory, glory as of the only Son from the Father\n\n<i>JOHN 1:14</i>`,
    `O Lord, let thy ear be attentive to the prayer of thy servant, and to the prayer of thy servants who delight to fear thy name; and give success to thy servant today, and grant him mercy in the sight of this man\n\n<i>NEHEMIAH 1:11</i>`,
    `And they said, "Believe in the Lord Jesus, and you will be saved, you and your household"\n\n<i>ACTS 16:31</i>`,
    `The steadfast love of the Lord never ceases, His mercies never come to an end; they are new every morning; great is thy faithfulness\n\n<i>LAMENTATIONS 3:22-23</i>`,
    `It is good that one should wait quietly for the salvation of the Lord\n\n<i>LAMENTATIONS 3:26</i>`,
    `The end of all things is at hand; therefore keep sane and sober for your prayers\n\n<i>1 PETER 4:7</i>`,
    `Cast your burden on the Lord, and He will sustain you; He will never permit the righteous to be moved\n\n<i>PSALM 55:22</i>`,
    `Practice hospitality ungrudgingly to one another\n\n<i>1 PETER 4:9`,
    `My beloved is mine and I am his, he pastures his flock among the lilies\n\n<i>SONG OF SOLOMON 2:16</i>`,
    `And above all these put on love, which binds everything together in perfect harmony\n\n<i>COLOSSIANS 3:14</i>`,
    `Little children, let us not love in word or speech but in deed and in truth\n\n<i>1 JOHN 3:18</i>`,
    `Be watchful, stand firm in your faith, be courageous, be strong\n\n<i>1 CORINTHIANS 16:13</i>`,
    `Let all that you do be done in love\n\n<i>1 CORINTHIANS 16:14</i>`,
    `A cheerful heart is a good medicine, but a downcast spirit dries up the bones\n\n<i>PROVERBS 17:22</i>`,
    `A wicked man accepts a bribe from the bosom to pervert the ways of justice\n\n<i>PROVERBS 17:23</i>`,
    `For God so loved the world that He gave His only Son, that whoever believes in Him should not perish but have eternal life\n\n<i>JOHN 3:16</i>`,
    `The Lord appeared to him from afar. I have loved you with an everlasting love; therefore I have continued my faithfulness to you\n\n<i>JEREMIAH 31:3</i>`,
    `To aspire to live quietly, to mind your own affairs, and to work with your hands, as we charged you;\n\n<i>1 THESSALONIANS 4:11</i>`,
    `But ignoring what they said, Jesus said to the ruler of the synagogue, "Do not fear, only believe"\n\n<i>MARK 5:36</i>`,
    `Be strong, and let your heart take courage, all you who wait for the Lord!\n\n<i>PSALM 31:24</i>`,
    `I will instruct you and teach you the way you should go; I will counsel you with my eye upon you\n\n<i>PSALM 32:8</i>`,
    `Therefore, my beloved, as you have always obeyed, so now, not only as in my presence but much more in my absence, work out your own salvation with fear and trembling\n\n<i>PHILIPPIANS 2:12</i>`,
    `Do all things without grumbling or questioning\n\n<i>PHILIPPIANS 2:14</i>`,
    `Him we proclaim, warning every man and teaching every man in all wisdom, that we may present every man mature in Christ\n\n<i>COLOSSIANS 1:28`,
    `Be not quick to anger, for anger lodges in the bosom of fools\n\n<i>ECCLESIASTES 7:9</i>`,
    `Better is the end of a thing than its beginning; and the patient in spirit is better than the proud in spirit\n\n<i>ECCLESIASTES 7:8</i>`,
    `For the protection of wisdom is like the protection of money; and the advantage of knowledge is that wisdom preserves the life of him who has it\n\n<i>ECCLESIASTES 7:12</i>`,
    `Though a sinner does evil a hundred times and prolongs his life, yet I know that it will be well with those who fear God, because they fear before Him;\n\n<i>ECCLESIASTES 8:12</i>`,
    `O Lord, thou art my God; I will exalt thee, I will praise thy name; for thou hast done wonderful things, plans formed of old, faithful and sure\n\n<i>ISAIAH 25:1</i>`,
    `Beloved, let us love one another; for love is of God, and he who loves is born of God and knows God\n\n<i>1 JOHN 4:7</i>`,
    `He who does not love does not know God; for God is love\n\n<i>1 JOHN 4:8</i>`,
    `My eyes are ever toward the Lord, for He will pluck my feet out of the net\n\n<i>PSALM 25:15</i>`,
    `The fear of man lays a snare, but he who trusts in the Lord is safe\n\n<i>PROVERBS 29:25</i>`,
    `He who heeds instruction is on the path to life, but he who rejects reproof goes astray\n\n<i>PROVERBS 10:17</i>`,
    `My help comes from the Lord, who made heaven and earth\n\n<i>PSALM 121:2</i>`,
    `The Lord is near to the brokenhearted, and saves the crushed in spirit\n\n<i>PSALM 34:18</i>`,
    `Father of the fatherless and protector of widows is God in his holy habitation\n\n<i>PSALM 68:5</i>`,
    `This is the day which the Lord has made; let us rejoice and be glad in it\n\n<i>PSALM 118:24</i>`,
    `A new commandment I give to you, that you love one another; even as I have loved you, that you also love one another\n\n<i>JOHN 13:34</i>`,
    `May the God of steadfastness and encouragement grant you to live in such harmony with one another, in accord with Christ Jesus\n\n<i>ROMANS 15:5</i>`,
    `That together you may with one voice glorify the God and Father of our Lord Jesus Christ\n\n<i>ROMANS 15:6</i>`,
    `Let your speech always be gracious, seasoned with salt, so that you may know how you ought to answer everyone\n\n<i>COLOSSIANS 4:6</i>`,
    `I love the Lord, because He has heard my voice and my supplications\n\n<i>PSALM 116:1</i>`,
    `Because He inclined His ear to me, therefore I will call on Him as long as I live\n\n<i>PSALM 116:2</i>`,
    `Gracious is the Lord, and righteous; our God is merciful\n\n<i>PSALM 116:5</i>`,
    `What shall I render to the Lord for all His bounty to me?\n\n<i>PSALM 116:12</i>`,
    `So Jacob served seven years for Rachel, and they seemed to him but a few days because of the love he had for her\n\n<i>GENESIS 29:20</i>`,
    `God said to Moses, "I am who I am." And He said, "Say this to people of Israel, 'I am has sent me to you'"\n\n<i>EXODUS 3:14</i>`,
    `For with God nothing will be impossible\n\n<i>LUKE 1:37</i>`,
    `And Mary said, "Behold, I am the handmaid of the Lord; let it be done to me according to your word." And the angel departed from her\n\n<i>LUKE 1:38</i>`,
    `Moreover choose able men from all the people, such as fear God, men who are trustworthy and who hate a bribe; and place such men over the people as rulers of thousands, of hundreds, of fifties, and of tens\n\n<i>EXODUS 18:21</i>`,
    `And He said, "My presence will go with you, and I will give you rest."\n\n<i>EXODUS 33:14</i>`,
    `And a cloud overshadowed them, and a voice came out of the cloud, "This is my beloved Son; listen to Him."\n\n<i>MARK 9:7</i>`,
    `Anxiety in a man's heart weighs him down, but a good word makes him glad\n\n<i>PROVERBS 12:25</i>`,
    `A slothful man will not catch his prey, but the diligent man will get precious wealth\n\n<i>PROVERBS 12:27</i>`,
    `The people who walked on darkness have seen a great light; those who dwelt in a land of deep darkness, on them has light shined\n\n<i>ISAIAH 9:2</i>`,
    `And when I go and prepare a place for you, I will come again and will take you to myself, that where I am you may also be\n\n<i>JOHN 14:3</i>`,
    `For where two or three are gathered in my name, there am I in the midst of them\n\n<i>MATTHEW 18:20</i>`,
    `But He gives more grace; therefore it says, "God opposes the proud, but gives grace to the humble"\n\n<i>JAMES 4:6</i>`,
    `Submit yourselves therefore to God. Resist the devil and he will flee from you\n\n<i>JAMES 4:7</i>`,
    `Draw near to God and He will draw near to you. Cleanse your hands, you sinners, and purify your hearts, you men of double mind\n\n<i>JAMES 4:8</i>`,
    `Humble yourselves before the Lord and He will exalt you\n\n<i>JAMES 4:10</i>`,
    `There is one lawgiver and judge, He who is able to save and to destroy. But who are you that you judge your neighbor?\n\n<i>JAMES 4:12</i>`,
    `Whereas you do not know about tomorrow. What is your life? For you are a mist that appears for a little time and then vanishes\n\n<i>JAMES 4:14</i>`,
    `Instead you ought to say, "If the Lord wills, we shall live and we shall do this or that"\n\n<i>JAMES 4:15</i>`,
    `I thank my God always when I remember you in my prayers\n\n<i>PHILEMON 1:4</i>`,
    `And I pray that the sharing of your faith may promote the knowledge of all the good that is ours in Christ\n\n<i>PHILEMON 1:6</i>`,
    `The Rock, His work is perfect; for all His ways are justice. A God of faithfulness and without inquity, just and right is He\n\n<i>DEUTERONOMY 32:4</i>`,
    `But I do not account my life of any value nor as precious to myself, if only I may accomplish my course and the ministry which I received from the Lord Jesus, to testify to the gospel of the grace of God\n\n<i>ACTS 20:24</i>`,
    `Truly, I say to you, whoever does not receive the kingdom of God like a child shall not enter it\n\n<i>LUKE 18:17</i>`,
    `But in your hearts reverence Christ as Lord. Always be prepared to make a defense to anyone who calls you to account for the hope that is in you, yet do it with gentleness and reverence;\n\n<i>1 PETER 3:15</i>`,
    `Do you not know that you are God's temple and that God's Spirit dwells in you?\n\n<i>1 CORINTHIANS 3:16</i>`,
    `If anyone destroys God's temple, God will destroy him. For God's temple is holy, and that temple you are\n\n<i>1 CORINTHIANS 3:17</i>`,
    `And you are Christ's; and Christ is God's\n\n<i>1 CORINTHIANS 3:23</i>`,
    `For the desires of the flesh are against the Spirit, and the desires of the Spirit are against the flesh; for these are opposed to each other, to prevent you from doing what you would\n\n<i>GALATIANS 5:17</i>`,
    `Look carefully then how you walk, not as unwise men but as wise, making the most of the time, because the days are evil\n\n<i>EPHESIANS 5:15-16</i>`,
    `Therefore do not be foolish, but understand what the will of the Lord is\n\n<i>EPHESIANS 5:17</i>`,
    `Because we are members of His body\n\n<i>EPHESIANS 5:30</i>`,
    `But there are also many other things which Jesus did; were every one of them to be written, I suppose that the world itself could not contain the books that would be written\n\n<i>JOHN 21:25</i>`,
    `Answer me when I call, O God of my right! Thou hast given me room when I was in distress. Be gracious to me, and hear my payer\n\n<i>PSALM 4:1</i>`,
    `The Lord is good to those who wait for Him, to the soul that seeks Him. It is good that one should wait quietly for the salvation of the Lord\n\n<i>LAMENTATIONS 3:25-26</i>`,
    `Let us test and examine our ways, and return to the Lord!\n\n<i>LAMENTATIONS 3:40</i>`,
    `For righteousness is immortal\n\n<i>WISDOM OF SOLOMON 1:15</i>`,
    `If riches are a desirable possessions in life, what is richer than wisdom who effects all things?\n\n<i>WISDOM OF SOLOMON 8:5</i>`,
    `You are all fair, my love; there is no flaw in you\n\n<i>SONG OF SOLOMON 4:7</i>`,
    `Even as the Son of man came not to be served but to serve, and to give His life as a ransom for many\n\n<i>MATTHEW 20:28</i>`,
    `Jesus Christ is the same yesterday and today and forever\n\n<i>HEBREWS 13:8</i>`,
    `And there is salvation in no one else, for there is no other name under heaven given among men by which we must be saved\n\n<i>ACTS 4:12</i>`,
    `And my God will supply every need of yours according to his riches in glory in Christ Jesus\n\n<i>PHILIPPIANS 4:19</i>`,
    `For My thoughts are not your thoughts, neither are your ways My ways, says the Lord\n\n<i>ISAIAH 55:8</i>`,
    `That your faith might not rest in the wisdom of men, but in the power of God\n\n<i>1 CORINTHIANS 2:5</i>`,
    `And he will be the stability of your times, abundance of salvation, wisdom, and knowledge; the fear of the Lord is his treasure\n\n<i>ISAIAH 6:33</i>`,
    `You will tread on the lion and the adder, the young lion and the serpent you will trample under foot. Because he cleaves to me in love, I will deliver him; I will protect him, because he knows My name\n\n<i>PSALMS 91:13-14</i>`,
    `But now put them all away: anger, wrath, malice, slander, and foul talk from your mouth\n\n<i>COLOSSIANS 3:9</i>`,
    `He must increase, but I must decrease\n\n<i>JOHN 3:30</i>`
];

function newVerse() {
    var randomNumber = Math.floor(Math.random() * verse.length);
    document.getElementById("verseDisplay").innerHTML = verse[randomNumber];
}